### ISSUE TITLE
打包了半天 打包不出来..有现成的apk？

### ISSUE THREAD

**Issue by amu1433** [WeihuaGu/receiptnotice#1]
提示app/key.properties 这个找不到

**Comment by WeihuaGu** [comment]
https://www.coolapk.com/apk/com.weihuagu.receiptnotice

酷安的地址，可以直接下。那个文件是用来包含签名的，修改下app下的build.gradle,把前面三行引入签名的删掉，然后下面的buildtype改成debug的就可以了
