### ISSUE TITLE
你好，大佬，问题反馈，不能POST提交

### ISSUE THREAD

**Issue by pan427pzh** [WeihuaGu/receiptnotice#10]
昨天下载了，0.2版本的进行测试。
华为手机，安卓9.0，DEBUG模式，能接受到通知，不能POST提交，不能保存post设置的地址。（该手机有提示开启存储权限，已开启）
oppo手机，（版本没看），DEBUG模式，不能接受到通知，也不能POST提交，也不能保存POST地址。（该手机未提示开启存储权限）
2部手机，都设置了软件的通知权限，以及支付助手的通知功能。
总结：
---------------------------------------------------------------------
软件接受到通知后，不能POST推送，设置POST地址后，软件重启，地址丢失。
软件对环境有什么要求。比如安卓的版本，需要开放权限。

**Comment by pan427pzh** [comment]
对了，是支付宝

**Comment by WeihuaGu** [comment]
软件重启，地址应该没丢失，因为设置过后是通过SharedPreferences保存在xml中的。
试下releases里的那个

应该不是安卓版本的问题，我也是安卓9.0,只不过用的lineage.

**Comment by pan427pzh** [comment]
是不是0.2版本的app-release.apk用的就是这个的，地址丢失。几个手机都是重启地址丢失

**Comment by pan427pzh** [comment]
0.1版本也测试过

**Comment by WeihuaGu** [comment]
这个加上在输入框里显示，然后再重启，应该就知道地址是不是丢失了

**Comment by pan427pzh** [comment]
这个是什么

**Comment by WeihuaGu** [comment]
@pan427pzh 试下地址还重启丢失不，如果可以直接更新下代码编译，如果不行，用这个我build好的debug版试一下 
[下载](https://github.com/WeihuaGu/asserversource/raw/master/app-debug.apk)

**Comment by pan427pzh** [comment]
发的这个debug版本的好像可以保存地址，设置地址后重启，会有一个灰色的地址，这个地址是之前设置过的。
不过依旧不能发送post，不知道为什么。

**Comment by pan427pzh** [comment]
对了，推送地址是没有错的，我复制的，也测试过的，不管post还是get访问都会有一个日志文件。软件没有访问设置的地址。

**Comment by WeihuaGu** [comment]
接收到支付宝或者微信的收款通知才会post的。
你能把adb logcat  | grep NLService发上来吗？或者点左下角的那个Log按钮，在你成功收到收款后，那里有没有一行NLService: post task postjson：？

**Comment by pan427pzh** [comment]
[https://www.szyytx.cn/respone.jpg](url)
这里有一张图片

**Comment by daniuwo** [comment]
后台应该用PUT方式接收数据，POST接不到的

**Comment by WeihuaGu** [comment]
@pan427pzh 可以再试下这个[debug版](https://github.com/WeihuaGu/asserversource/raw/master/app-debug.apk)
应该可以推送了

**Comment by pan427pzh** [comment]
@WeihuaGu 谢谢你大佬，你真是一个好人，我试下

**Comment by daniuwo** [comment]
> 对了，推送地址是没有错的，我复制的，也测试过的，不管post还是get访问都会有一个日志文件。软件没有访问设置的地址。



> @pan427pzh 可以再试下这个[debug版](https://github.com/WeihuaGu/asserversource/raw/master/app-debug.apk)
> 应该可以推送了

推送时间可以加上（秒）吗  可以更精准对单

**Comment by pan427pzh** [comment]
https://www.szyytx.cn/static/images/pay.png
大佬，你好，后面的这个版本可以POST推送了。有个问题请教一下，不能获取到付款备注吗，以及付款理由和支付宝订单号这些参数吗。

**Comment by pan427pzh** [comment]
哦，图片里面的那个金额为空

**Comment by pan427pzh** [comment]
@WeihuaGu

**Comment by WeihuaGu** [comment]
@daniuwo  应该已经加上了秒。
@pan427pzh 这回这个[debug版](https://github.com/WeihuaGu/asserversource/raw/master/app-debug.apk)应该可以提取到金额了。

**Comment by pan427pzh** [comment]
@WeihuaGu 大佬，那个备注和订单详情能获取的到不

**Comment by WeihuaGu** [comment]
@pan427pzh 刚刚那个debug版有点问题，还是一样的地址，我又上传了下。
不能获得备注和订单详情，因为监控通知栏的化，通知栏只有时间，金额，没有那些。也就是说你只能通过时间加上金额来判断 ：（

**Comment by pan427pzh** [comment]
@WeihuaGu 明白了，谢谢大佬。大佬可以在项目里面放个打赏方式，回头过来打赏大佬。

**Comment by WeihuaGu** [comment]
：）就是的，运气好说不定还会有一两块的打赏的，呵呵
目前都是权宜的办法，但是引酷友的一句话："营业执照是不可能，这辈子都不可能有的"
