### ISSUE TITLE
你好，我在真机上测试，有时候log.d的显示会延迟一条

### ISSUE THREAD

**Issue by Luckyyyyyyy** [WeihuaGu/receiptnotice#11]
比如说我微信发送通知 “1”，日志页面只会显示到 包名是com.tencent.com 就停了，我再发一次微信通知“2”，才会把上条的信息补完，然后显示*******，然后后面每次都延迟一条，要手动滑动屏幕才会输出最新的log.请问大佬你有这样的情况吗？

**Comment by WeihuaGu** [comment]
点返回，再点那个log按钮进入试下。我一般用adb命令，adb logcat,因为这个是官方显示日志的方法，比较没问题。
