### ISSUE TITLE
是不是用了微信收款助手，就没法用了

### ISSUE THREAD

**Issue by hanliux** [WeihuaGu/receiptnotice#12]
我的微信收款，日志上记录都有，但是被当作是检测之外的其它通知了。

**Comment by WeihuaGu** [comment]
截下图，我要看下，应该改下就能行吧。

**Comment by hanliux** [comment]
![image](https://user-images.githubusercontent.com/16254822/54862261-ec71c400-4d72-11e9-9ea8-68ae3ab6ae59.png)
就是用了微信的小账本，就是这样的通知，我觉得可以简化消息，干脆主要匹配工作交给接口做，只要匹配的“支付” 收款字样就推送消息到接口，由接口来处理判断是否是收款信息。

**Comment by WeihuaGu** [comment]
@hanliux 可以试一下这个新编译的debug版本，看看行不行。
https://github.com/WeihuaGu/asserversource/raw/master/app-debug.apk

**Comment by hanliux** [comment]
![image](https://user-images.githubusercontent.com/16254822/54867439-3a121f00-4dbb-11e9-8106-cbacfbf9b9c0.png)
测试了一下，支付宝协议生成的动态金额码，是这样的通知，也识别不了。

**Comment by hanliux** [comment]
这个新版能识别 微信收款助手的 消息了。
