### ISSUE TITLE
能否在Django上部署？

### ISSUE THREAD

**Issue by fengjunCN** [WeihuaGu/receiptnotice#13]
我的服务器是ubuntu16 Django 服务器，能否在这上面部署相应的程序？还有个个人小问题请教：安卓端APP监听到付款信息后POST给服务器网关信息，服务器如何响应该信息，该信息处理后的结果如何反馈到客户端浏览器（个人觉得因为POST不是客户端浏览器发起的，不知服务器如何准确的把信息反馈到客户端浏览器）。谢谢！

**Comment by WeihuaGu** [comment]
POST给服务器->服务器存入服务器的数据库
客户端再给服务器发请求->服务器返回是否有支付记录
