### ISSUE TITLE
针对通知栏不显示金额的通知怎么办？

### ISSUE THREAD

**Issue by Zhouxuan-C** [WeihuaGu/receiptnotice#15]
比如使用 AA 收款，通知栏是看不到收到的金额的。对于这种情况有什么办法吗？

**Comment by WeihuaGu** [comment]
如果通知里没有金额，使用这种方法就获取不到。

**Comment by Zhouxuan-C** [comment]
> 如果通知里没有金额，使用这种方法就获取不到。

嗯  我再想想办法
