### ISSUE TITLE
能获取到更多的支付信息吗  

### ISSUE THREAD

**Issue by zhupengxiang** [WeihuaGu/receiptnotice#16]
能获取到更多的支付信息吗  比如备注   付款人信息什么的   
还有怎么保证服务不被进程杀死    因为不是在服务实时上传数据吗

**Comment by Zhouxuan-C** [comment]
我也想获取不在通知栏显示的信息

**Comment by zhupengxiang** [comment]
@Zhouxuan-C  能搞到username什么的吗

**Comment by abcweihua** [comment]
那些信息可能要付费开发的哦
