### ISSUE TITLE
能否新增QQ钱包收款？

### ISSUE THREAD

**Issue by lixiaolong2** [WeihuaGu/receiptnotice#17]
能否新增QQ钱包收款？让QQ收款也能通知

**Comment by WeihuaGu** [comment]
这个应该不难，但是我没有用过qq收款，你能截上一张有qq收款的log截图吗

**Comment by WeihuaGu** [comment]
@lixiaolong2  我试了下qq收款，扫二维码的要求双方都实名验证，用qq号的竟然发过去没任何提示，要在一样的那个里找接受确认……我估计是不行了
