### ISSUE TITLE
能否监听到收钱吧的收款信息？

### ISSUE THREAD

**Issue by yanpengqing** [WeihuaGu/receiptnotice#19]
如题

**Comment by WeihuaGu** [comment]
@yanpengqing 这个手机有通知吗？通知栏有通知应该就可以。

**Comment by lixiaolong2** [comment]
包名 com.wosai.cashbar  
标题 收钱吧
内容1 成功收款0.53元,来自微信
内容2 成功收款0.12元,来自支付宝
内容3 成功收款0.12元,来自XXX(还有其他的,建议直接传类型收钱吧-XXXX)

**Comment by WeihuaGu** [comment]
现在收钱吧微信的type是cashbar-wechat，支付宝的type是cashbar-alipay,其它的是cashbar-XXX.

**Comment by lixiaolong2** [comment]
@WeihuaGu 测试已可以推送。

**Comment by WeihuaGu** [comment]
@lixiaolong2 好的，感谢。
