### ISSUE TITLE
微信收款没有推送信息

### ISSUE THREAD

**Issue by maitao** [WeihuaGu/receiptnotice#20]
微信收款语音提醒和显示在收款助手里面了，获取不到，请问这个有解决方案吗

**Comment by WeihuaGu** [comment]
@maitao 我没用过收款助手……，是进入收款账本小程序里，然后怎么做，我的收款还是提示微信支付收款XX元（朋友到店).
之前问题#12 提过添加这个，然后我按照给的这个截图添加了这个，但是这个是怎么用的？

**Comment by WeihuaGu** [comment]
还有就是，你的微信是不是在前台，我猜测是不是这种情况下，它要后台才给通知？
