### ISSUE TITLE
银联云闪付不能抓取

### ISSUE THREAD

**Issue by lalavcstudy** [WeihuaGu/receiptnotice#21]
能增加银联云闪付抓取功能吗？
标题是：消息推送
内容是：云闪付收款1元。

**Comment by WeihuaGu** [comment]
@lalavcstudy 包名 是啥

**Comment by lalavcstudy** [comment]
不好意思忘了写了，
包名:com.unionpay

**Comment by WeihuaGu** [comment]
应该是可以使用了，你可以用release里发布的debug版测试下
