### ISSUE TITLE
你好能增加工银商户之家吗

### ISSUE THREAD

**Issue by lalavcstudy** [WeihuaGu/receiptnotice#22]
你好能增加工银商户之家吗
前几天测试云闪付发现大部分时间不弹消息，十分不好用，后来发现工银商户之家好像可以正常弹消息。
标题是：工银商户之家
内容是：您已收到1元，点击查看详情。
包名：com.icbc.biz.elife

感谢！

**Comment by WeihuaGu** [comment]
可以试一下，release里的那个debug的最新版本

**Comment by lalavcstudy** [comment]
感谢！

**Comment by WeihuaGu** [comment]
@lalavcstudy 我研究了下云闪付，云闪付对申请的商家收款二维码有推送通知，但是首页的那个收款二维码好像没有直接推送，要么就有延迟。
但是我发现云闪付支持小米推送，并且通过小米推送的很及时，且首页的那个收款码也支持
