### ISSUE TITLE
编译不过去

### ISSUE THREAD

**Issue by eight-26** [WeihuaGu/receiptnotice#24]
报错提示：Could not resolve com.gcssloop.util:encrypt:1.0.2
gcssloop 网站暂停维护，已经打不开了！
能不能连依赖包一起打包一份啊？拜托！

**Comment by WeihuaGu** [comment]
新的安卓版本上，那个库的AES有问题，我才只用了des。 我考虑换掉这个加密的库，但不知道哪个现在好用

**Comment by WeihuaGu** [comment]
@eight-26 我已经去除了对于com.gcssloop.util:encrypt库的依赖。

**Comment by eight-26** [comment]
谢谢啦，我现在去编译试试
