### ISSUE TITLE
微信收款都被移至收款助手里面了，有什么解决办法吗？

### ISSUE THREAD

**Issue by onlyyoulove** [WeihuaGu/receiptnotice#25]
收款助手也一样有语音提示的，提示内容也一样，但就是读取不到了。
我几个号收款，发现好像是只要收款总额达到一定金额，微信就自动转到手款助手了。
收款助手提示：微信收款xx元

**Comment by WeihuaGu** [comment]
@onlyyoulove 微信关闭语音提醒试一下。

**Comment by WeihuaGu** [comment]
关联#20

**Comment by WeihuaGu** [comment]
问题讨论：
- 1.大致收款到多少时就不给通知栏通知移动到收款助手？
- 2.不给通知与微信在不在前台有没有关系，与微信在不在后台有没有关系。
- 3.跟微信版本有没有关系，是不是所有版本都是如此。play版与国内版是否一样，当把微信后台杀掉，使用谷歌FCM推送时，给不给通知？
