### ISSUE TITLE
用华为的手机打开后 点log按钮

### ISSUE THREAD

**Issue by adongtt** [WeihuaGu/receiptnotice#26]
什么内容都不显示，这是表示监听的服务没启动起来吗？权限有打开

**Comment by WeihuaGu** [comment]
log展示按道理不需要任何权限。我使用的是pedrovgs/Lynx的库，它的源码也其实只是执行了logcat命令:
```
process = Runtime.getRuntime().exec("logcat -v time");
```
然后用process.getInputStream获得标准输出。

**Comment by WeihuaGu** [comment]
如果可以的化，你可以在开发者选项中开启usb调试，然后插到电脑上，用`adb logcat NLService:V`看看能不能显示出来log。

**Comment by adongtt** [comment]
把NLService消掉,有log显示，提示如下图

**Comment by adongtt** [comment]
我把NLService去掉 显示如图

**Comment by adongtt** [comment]
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxgetmsgimg?&MsgID=1316692703007361018&skey=%40crypt_a944ddd5_dfd4e7cfc1c060aa65554e03aa421ed2

把NLService去掉显示如图

**Comment by WeihuaGu** [comment]
那就不是log的问题，可能确实服务被杀了。具体，如果你会开启开发者选项，然后查看正在运行的服务。
receiptnotice会开启两个服务，一个是NLService,这个是用来监听的服务，另一个是NotificationCollectorMonitorService,这个是NLService的守护进程。看看这两个服务有没有运行。

**Comment by adongtt** [comment]
> 那就不是log的问题，可能确实服务被杀了。具体，如果你会开启开发者选项，然后查看正在运行的服务。
> receiptnotice会开启两个服务，一个是NLService,这个是用来监听的服务，另一个是NotificationCollectorMonitorService,这个是NLService的守护进程。看看这两个服务有没有运行。

这两个进程是有在的 但是就是没有NLService的任何log出现

**Comment by WeihuaGu** [comment]
试一下推送是否正常，看看推送后在推送记录里有没有东西。

**Comment by WeihuaGu** [comment]
关联#28
