### ISSUE TITLE
file_get_contents('php://input')内容为空

### ISSUE THREAD

**Issue by itispip** [WeihuaGu/receiptnotice#27]
v0.9, type=alipay

回调确实发生了，但是服务端最简单的测试代码解析JSON，内容为空，什么都没有。

$request = file_get_contents('php://input');
$request = json_decode($request, true);

// 解析对象返回字符串
$money = $request->money; //  返回支付金额
$title = $request->title; //返回支付标题
$content = $request->content; // 返回支付内容
$time = $request->time; // 返回支付时间

以上全部为空值

**Comment by WeihuaGu** [comment]
php 解码函数的那个true改成false 试试

**Comment by itispip** [comment]
> php 解码函数的那个true改成false 试试

试过了，没有用。因为无论在json_decode之前还是之后，用var_dump打印出来的$request值都是空。似乎App发起回调但没有post任何数据过来。

**Comment by WeihuaGu** [comment]
@itspip app的推送记录有记录吗？如果在json_decode之前，打印还是空的化，构建一个最简单的echo服务，只是单纯的返回post的内容

**Comment by WeihuaGu** [comment]
如果没有的化，可以填我的这个 https://netutil.now.sh/echo
它会返回post的内容，然后在推送记录里再看看有没有记录

**Comment by itispip** [comment]
> 如果没有的化，可以填我的这个 https://netutil.now.sh/echo
> 它会返回post的内容，然后在推送记录里再看看有没有记录

1. 推送记录有时候有，有时候没有。从昨天到今天，我测试了几十次推送了，只有3次在APP里看到了推送记录

2. 尽管没有记录，但是推送确实发生了，因为我在网站端的回调URL确实被唤起试图decode json了

3. 已经尝试了推送到你的URL。手机端推送记录里没有显示

**Comment by WeihuaGu** [comment]
那就只能看logcat了，log 怎么显示的。推送前它会输出要post 的字符串json,推送后，会输出成功还是失败

**Comment by WeihuaGu** [comment]
点那个log按钮，或者显示更好点用adb logcat | grep NLService

**Comment by itispip** [comment]
log按钮里，设为debug，如果filter NLService，什么都没有；如果不filter全部显示，最多的纪录是类似于

system.out( 5799): null

这样的

**Comment by WeihuaGu** [comment]
看下正在运行的服务，receiptnotice会开启两个服务，一个是NLService,这个是用来监听的服务，另一个NotificationCollectorMonitorService,这个是NLService的守护进程。看看这两个服务有没有运行。确保NLService这个服务是运行着的。如果可以截一下刚试过推送后的logcat ,别加过滤。

**Comment by itispip** [comment]
收款推送在后台锁定的情况下，安卓6.0的手机，开发人员选项--正在运行的服务-收款推送，1个进程连哥哥服务，两个服务都是已启动。

其中的NLService服务下点设置，进入“通知使用权限”，收款推送的权限已经赋予
![Screenshot_2019-06-08-11-24-28](https://user-images.githubusercontent.com/51486900/59141478-4f710f80-89e0-11e9-9396-3d2d77112df4.png)

**Comment by tsqgw** [comment]
我的正常，能收到  我都写到数据库了

**Comment by WeihuaGu** [comment]
@itispip 从截图上来看，展示log的那个lynx.model.Logcat想给system.out标准输出流输出点东西，却输出了null.
不能用应用自带的这个来看安卓的logcat。
如果想知道怎么回事，看来要用adb logcat命令了。
要有一台装了adb 的电脑，然后开发者选项开启usb调试，然后使用adb logcat 来查看。还是先看看adb logcat | grep NLService看有没有。
没有的化不加过滤，直接adb logcat。

**Comment by onlyyoulove** [comment]
$json = file_get_contents("php://input");
	//echo $json;
	$obj = json_decode($json);
	$payfee = $obj->money;//支付金额
	$paytitle = $obj->type;//支付方式
这是我的，给你参考一下，我的支付宝正常使用。就是微信不行了，移到收款助手了，现在这个 app接收不到通知了。
