### ISSUE TITLE
没看懂怎么通过收款时间来区分,po主能讲解下嘛?

### ISSUE THREAD

**Issue by zohar-soul** [WeihuaGu/receiptnotice#29]
`3.考虑时间因素 我们假定用户购买的时间也是随机的，如果我们只考虑小时和分钟数，那么这个时间的概率大概是p(C)=1/13*1/60=1/780`

如何将付款时间和订单生成时间对应起来呢?
还是说付款时间有别的用法呢?

谢谢

**Comment by WeihuaGu** [comment]
一般是先生成个订单，然后有个订单的生成时间。你再规定个支付的时间限制,如果过了，就重新来一次重新计算。只要真正收款的时间在这个时间限制内就可以。

**Comment by WeihuaGu** [comment]
时间设个三五分钟，不是太长的就问题不大。或者别的招，反正就是你知道用户这边要支付了，有个时间，然后你这边收到款有个时间,这两个时间非常接近再加上金额，就算对上了。

**Comment by zohar-soul** [comment]
@WeihuaGu 了解了
谢谢啦
