### ISSUE TITLE
没有收到任何通知信息，没有打印日志

### ISSUE THREAD

**Issue by wangsai2018** [WeihuaGu/receiptnotice#3]
华为手机是api 19  和  27  的
两个都能安装，使用微信支付，没有监听到任何消息，也没有打印日志

**Comment by wangsai2018** [comment]
通知权限也给了呀，是不是手机还有什么其他设置

**Comment by WeihuaGu** [comment]
先看下有没有运行，在正在运行的服务里找下有没有receiptnotice.或者直接用adb shell ps 打下所有进程，如果后台在运行，里面有一条是com.weihuagu.receiptnotice
![](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/tmp.jpg)

**Comment by cbw7172002** [comment]
收到的是{"money":"null","title":"微信支付","content":"收款到账通知","time":"2019-03-04 11:15"｝
根本没 金额 能加QQ:175510896了解么

**Comment by WeihuaGu** [comment]
上面收到的是服务器收到的还是这个应用日志打印的？是NLService: post task postjson：后面的内容吗？
```
03-05 13:29:01.409  3460  3460 D NLService: 开始准备进行post
03-05 13:29:01.434  3460  1717 D NLService: post task  url:http://192.168.1.112:3000/bill/getedmoney/
03-05 13:29:01.434  3460  1717 D NLService: post task postjson:{"money":"1.17","time":"2019-03-05 13:29","title":"微信支付","content":"[3条]微信支付: 微信支付收款1.17元(朋友到店)"}
03-05 13:29:02.149  3460  3460 D NLService: Post Receive-returned post string
03-05 13:29:02.149  3460  3460 D NLService: {"code":200,"msg":"新的收入记录已储存"}
```

**Comment by cbw7172002** [comment]
有时候行，有时候不行，搞不懂

**Comment by WeihuaGu** [comment]
post task postjson后面也是时有时没有？因为post的内容就是postjson后面的。然后这个后面的内容就是读通知栏得到的。

**Comment by cbw7172002** [comment]
我知道  微信版本最新的是不行的 要降低版本 我用的6.6.6    而且还要开提示音

**Comment by WeihuaGu** [comment]
我用的微信版本是7.0.0，是不是微信如果就在前台显示，它就不用通知栏通知了
