### ISSUE TITLE
可否增加重试机制

### ISSUE THREAD

**Issue by flyoverGu** [WeihuaGu/receiptnotice#30]
可否增加重试机制, 特定返回就不再重试

**Comment by WeihuaGu** [comment]
这样的问题是等于强制了返回的结果

**Comment by WeihuaGu** [comment]
比如返回什么应该重试呢？倒是可以在请求失败时选择重试

**Comment by flyoverGu** [comment]
返回状态非200的时候重试,  隔几秒重试下,  重试个几次就行

**Comment by WeihuaGu** [comment]
我想想怎么弄好…

**Comment by WeihuaGu** [comment]
关联#31

**Comment by onlyyoulove** [comment]
> 关联[＃31](https://github.com/WeihuaGu/receiptnotice/issues/31)

看到您说已经增加了失败重试功能，可能生成app让下载吗？您给的好像是代码，我不懂如何去生成一个安卓app，谢谢。
