### ISSUE TITLE
请求增加推送失败重试功能

### ISSUE THREAD

**Issue by onlyyoulove** [WeihuaGu/receiptnotice#31]
您软件的推送日志自带有个推送结果，我猜想应该是根据http返回是否200来判断的，您日志里用返回结果true或false表示，能不能根据这个，如果推送出现false，重新推送一下，因为有时因为高峰期服务器网络差，或者手机自身网络差，会出现推送失败，因为关系到钱，不到账客户会比较敏感，会投诉。所以请求增加推送失败重试功能，望考虑。

**Comment by WeihuaGu** [comment]
感谢建议。现在的代码，直接用的请求体＜response-body＞是不是null来返回的这个true或者false。失败重新推送应该不难实现。

**Comment by WeihuaGu** [comment]
已经增加了推送失败重试功能，如果出现问题，可以到 [问题30](https://github.com/WeihuaGu/receiptnotice/issues/30)发送情况,就不重复多个了。

**Comment by WeihuaGu** [comment]
@onlyyoulove 我编译了一个临时版本，可以在release的那个最新debug版里下载.
