### ISSUE TITLE
微信收款商业版 首单的问题

### ISSUE THREAD

**Issue by hanliux** [WeihuaGu/receiptnotice#33]
首单的信息是这样的 “开门大吉， 首位顾客收款￥99.99元”  app能够获取信息并推送，但就是没有金额。

**Comment by WeihuaGu** [comment]
那后面的能正常显示金额吗？微信是从内容里找XX收款XX元,然后提取金额的，因为中间多了个￥的符号所以金额没正常提取。

**Comment by hanliux** [comment]
后面的收款信息都是正常的。
