### ISSUE TITLE
微信可以，支付宝不行完全没有

### ISSUE THREAD

**Issue by cbw7172002** [WeihuaGu/receiptnotice#4]

**Comment by ientium** [comment]
完全收不到啊，您的微信是什么版本的？

**Comment by cbw7172002** [comment]
> 完全收不到啊，您的微信是什么版本的？

可以收到  哎 我调整了下  但是这个APP 好像有点问题  过一会就不行了

**Comment by WeihuaGu** [comment]
要看是后台被杀了，还是后他正常，程序抽风

**Comment by cbw7172002** [comment]
> 要看是后台被杀了，还是后他正常，程序抽风

全新手机测试的，过一晚上就不行了 ，  还有什么好的解决办法没呀

**Comment by cbw7172002** [comment]
> 要看是后台被杀了，还是后他正常，程序抽风

老大 能不能加个心跳哦，我觉得加个心跳包好些

**Comment by WeihuaGu** [comment]
什么系统？先加白名单

**Comment by cbw7172002** [comment]
> 什么系统？先加白名单

金立S9  安卓系统呀

**Comment by cbw7172002** [comment]
> > 什么系统？先加白名单
> 
> 金立S9 安卓系统呀

不用加  我白天运行都可以的   过了一晚上就不行了

**Comment by WeihuaGu** [comment]
不行的时候，用adb logcat 看下到底有没有在后台。

**Comment by cbw7172002** [comment]
> 不行的时候，用adb logcat 看下到底有没有在后台。或者是不是重启就完蛋了。

我用的是真机，运行这个命令还要链接USB

**Comment by WeihuaGu** [comment]
手机可以装个终端应用，挺方便的，推荐你个软件，叫termux,超级好用

**Comment by WeihuaGu** [comment]
我觉得还是应该应用里写个查看日志的……

**Comment by cbw7172002** [comment]
> 手机可以装个终端应用，挺方便的，推荐你个软件，叫termux,超级好用

对，谢谢老大，加个Q嘛  175510896

**Comment by WeihuaGu** [comment]
不怎么用QQ,你可以用邮箱，我比较喜欢用这个，老古董了：）

**Comment by cbw7172002** [comment]
好久更新了给我说下嘛 ，我觉得有输入地址的还是好，很多个人支付的APP都没，都是配套的

**Comment by WeihuaGu** [comment]
嗯，知道了。

**Comment by ientium** [comment]
华为的怎么设白名单，没弄明白

**Comment by cbw7172002** [comment]
> 华为的怎么设白名单，没弄明白

不需要

**Comment by ientium** [comment]
最好有个日志输出一下，知道是因为我的Post不对，还是程序没驻留，还是没抓到信息，我这个完全没反应...

**Comment by cbw7172002** [comment]
> 最好有个日志输出一下，知道是因为我的Post不对，还是程序没驻留，还是没抓到信息，我这个完全没反应...

你自己模拟提交一个撒 后端没问题了 在填写地址

**Comment by ientium** [comment]
从Apache服务器的访问日志来看，完全没有手机Post的记录，这是我手机的安全限制呢？还是微信的版本过高呢？华为P9 Plus  微信7.0.3

**Comment by WeihuaGu** [comment]
@ientium  adb logcat | grep NLService 在发送post时，如果这个程序运行正常，它会显示类似这样日志
```
03-05 13:29:01.409  3460  3460 D NLService: 开始准备进行post
03-05 13:29:01.434  3460  1717 D NLService: post task  url:http://192.168.1.112:3000/bill/getedmoney/
03-05 13:29:01.434  3460  1717 D NLService: post task postjson:{"money":"1.17","time":"2019-03-05 13:29","title":"微信支付","content":"[3条]微信支付: 微信支付收款1.17元(朋友到店)"}
03-05 13:29:02.149  3460  3460 D NLService: Post Receive-returned post string
03-05 13:29:02.149  3460  3460 D NLService: {"code":200,"msg":"新的收入记录已储存"}
```

**Comment by ientium** [comment]
在shell里按你的命令打完
HWVIE:/ $ logcat | grep NLService
完全没有日志输出...

**Comment by ientium** [comment]
adb shell ps | grep "com.weihuagu.receiptnotice"
STDIN
u0_a197      15621   755 2551844  52440 0                   0 S com.weihuagu.receiptnotice

**Comment by WeihuaGu** [comment]
那adb logcat | grep NLService 呢？有时候进入手机shell，会因为权限不足打印不出来log

**Comment by WeihuaGu** [comment]
https://github.com/WeihuaGu/receiptnotice/releases/tag/v0.2

**Comment by hanliux** [comment]
我这里正好相反，支付宝可以，但微信没反应，日志里是有微信收款信息的，但是没有被当作该post的通知。
