### ISSUE TITLE
建议deviceid在推送给post地址时，将uuid作为必传项

### ISSUE THREAD

**Issue by gouguoyin** [WeihuaGu/receiptnotice#41]
为防止设备过多，将自定义的deviceid设为相同时造成无法区分设备，建议在推送给post地址时deviceid的格式为：自定义标识符-uuid，如{"deviceid":"huawei-00805F9B34FB"}

**Comment by WeihuaGu** [comment]
不自定义时默认是UUID,自定义时按自定义。我当时这样做的原因是，觉得自定义时可以直接设置成不一样的，这样的好处是便于服务器检验。
自定义标识符-uuid，我觉得这也不错，可以增加上这个选项。

**Comment by gouguoyin** [comment]
或者将uuid作为单独字段回传给post也行，如{"deviceid":"huawei","uuid":"00805F9B34FB"}，deviceid设置了就传，没设置就传空。个人觉得还是自定义标识符-uuid格式好些，服务端需要uuid只需要将 自定义标识符-uuid 用-切割处理下即可。

**Comment by WeihuaGu** [comment]
嗯，所以我觉得加个deviceid后缀uuid的选项就行，需要选上就按照你说的这个格式推就行了。
