### ISSUE TITLE
建议保存已设置的post地址

### ISSUE THREAD

**Issue by gouguoyin** [WeihuaGu/receiptnotice#43]
现在APP每次重新打开post地址就清空了，建议像设置里的其他参数一样保存已设置的值

**Comment by WeihuaGu** [comment]
这个好办，当点击编辑框时，下面给个当前的提示，点击就把当前的弄上去

**Comment by gouguoyin** [comment]
为什么点击才把当前的弄上去，而不是直接在编辑框里显示出来？

**Comment by WeihuaGu** [comment]
本身一直就有提示，需要编辑时再这样做的好处是清楚，需要时再编辑。毕竟服务的地址不会一直变。

**Comment by WeihuaGu** [comment]
另一个好处是区分了状态，而不是一直显示编辑状态，这样不便于区分。
另外还可以给提示的列表添加前一次，前两次的，选择之后方便编辑

**Comment by zhengxiaozhu** [comment]
能否加我好友 1550186371
