### ISSUE TITLE
建议增加重复推送频率设置

### ISSUE THREAD

**Issue by gouguoyin** [WeihuaGu/receiptnotice#44]
建议增加重复推送间隔设置，单位秒，比如推送频率设为10s，重复次数设为3，那么推送失败后，会在10s、20s、30s后再次通知

**Comment by WeihuaGu** [comment]
意义不大，因为获取不到订单大，时间长了就没法判断了

**Comment by gouguoyin** [comment]
现在是推送失败后多长时间推送一次？这样做的好处是把控制权交到用户手里，用户可以根据自己的实际情况来设置间隔，肯定也不会设很长。

**Comment by WeihuaGu** [comment]
是立即重复，我的测试是，如果是服务器出问题，进行一次推送的等待时间就会变长，你设置几次后，如果可以就成功了，不可以，等可以推送时，它的时效性就过去了。所以我当时就只设置了次数而没有设置时间。

**Comment by gouguoyin** [comment]
立即重复?假设设置的是重复三次，三次是同时立即请求post地址吗？

**Comment by WeihuaGu** [comment]
另外我给了一个socket echo server的功能的想法是，是你这边查询支付之前，可以查询这个设备是否在线，在线再获取服务器接收来的推送。但是这个功能做的还不是很好，是将就用的地步。

**Comment by WeihuaGu** [comment]
不是，是顺次的。

**Comment by gouguoyin** [comment]
每次之间间隔多少？我提的这个建议主要是参考微信和支付宝异步通知失败的处理。
微信支付在通知一直不成功的情况下，总共会发起10次通知，每次通知时间距离最近一次的间隔为15/15/30/180/1800/1800/1800/1800/3600，单位为秒。
支付宝支付25小时以内完成8次通知，通知的间隔频率一般是：4m,10m,10m,1h,2h,6h,15h。

**Comment by gouguoyin** [comment]
我明白了，你的是第一次通知失败，立即通知第二次，第二次通知失败，马上再通知第三次，以此类推，是这样吗？

**Comment by WeihuaGu** [comment]
对的。
