### ISSUE TITLE
设置地址http://192.168.1.111/receiptnotice/test.php，但是获取到通知以后没有发送请求

### ISSUE THREAD

**Issue by hevenangel** [WeihuaGu/receiptnotice#45]
设置地址http://192.168.1.111/receiptnotice/test.php，但是获取到通知以后没有发送请求
没有设置uuid,
没有设置des
设置里内容没有操作，只设置了请求地址。局域网服务器没有接收到请求，这是怎么回事?

**Comment by gouguoyin** [comment]
看你写的post地址是用php写的，客户端传给post地址的是json数据，不能直接用$_POST接收，要用file_get_contents("php://input")来接收

**Comment by hevenangel** [comment]
我在服务器上没有接收数据，只是记录是否发送了请求，现在服务器上没有请求记录。客户端上能正常获取title和支付金额，地址设置正确，手机浏览器可以访问。但是APP只是获取了通知栏信息，没有发送请求到服务器

**Comment by WeihuaGu** [comment]
推送记录里有内容吗？log是什么情况？

**Comment by hevenangel** [comment]
推送记录里没有内容，服务器也没有请求记录

**Comment by hevenangel** [comment]
是否是设置POST地址以后，还需要开启 推送服务？如果是，在哪里开启呢？现在能够正常监听到通知栏消息，但是无法根据地址发送请求，由于是本地测试，填写的是http://ip/.../test.php文件.apache服务器上也没有相应的记录

**Comment by WeihuaGu** [comment]
按理说，只设置推送地址，啥都不用设置了

**Comment by WeihuaGu** [comment]
你能把log的截图发上来不

**Comment by hevenangel** [comment]
如图，请求地址，手机浏览器可以请求，测试过。
![Screenshot_2019-09-12-10-03-52-292_com weihuagu r](https://user-images.githubusercontent.com/28133672/64748617-4f376180-d545-11e9-8dd8-e4ec418ce7dc.png)
![Screenshot_2019-09-12-10-04-35-794_com weihuagu r](https://user-images.githubusercontent.com/28133672/64748618-50688e80-d545-11e9-8f07-0e75d9f36ddf.png)
![Screenshot_2019-09-12-10-04-42-576_com weihuagu r](https://user-images.githubusercontent.com/28133672/64748622-52cae880-d545-11e9-8752-5b3613229666.png)
![Screenshot_2019-09-12-10-04-49-764_com weihuagu r](https://user-images.githubusercontent.com/28133672/64748627-55c5d900-d545-11e9-832e-16d047b74775.png)
![Screenshot_2019-09-12-10-04-53-882_com weihuagu r](https://user-images.githubusercontent.com/28133672/64748631-56f70600-d545-11e9-84e6-557884c54874.png)
这是手机浏览器请求的记录：
![image](https://user-images.githubusercontent.com/28133672/64748661-755d0180-d545-11e9-8758-91a49093ddb3.png)

**Comment by WeihuaGu** [comment]
日志的截图,你是支付，不是收款啊

**Comment by hevenangel** [comment]
感谢，我好像两个支付宝弄混了，我试试。

**Comment by hevenangel** [comment]
![image](https://user-images.githubusercontent.com/28133672/64752389-fd490880-d551-11e9-82f1-9a7a99c7d1c9.png)
感谢，果然人多就是力量大。我这要是自己看，看到下辈子也不会发现
