### ISSUE TITLE
支付宝转账是否可以获取备注信息

### ISSUE THREAD

**Issue by xinlanlan** [WeihuaGu/receiptnotice#46]
支付宝转账的时候获取金额为0.0，如果有备注的话，app是否可以监听到备注信息，还有就是短信监听是否可以监听到手机号码。能否吧手机号码字段加上
大神是不是在做云闪付呀，云闪付最近支持了吗

**Comment by WeihuaGu** [comment]
获取不到备注。应该可以获取短信号码，所以这个字段应该能加上。云闪付是支持的。
