### ISSUE TITLE
是否可以支持农信易扫app到帐？

### ISSUE THREAD

**Issue by xinlanlan** [WeihuaGu/receiptnotice#48]
最近农信的聚合码比较多，是否可以增加支持？
农信的收款到帐消息格式是：

收款通知
一笔收款交易已完成，金额0.10元

**Comment by WeihuaGu** [comment]
可以添加。

**Comment by xinlanlan** [comment]
大佬什么时候更新呀~👀

**Comment by WeihuaGu** [comment]
这几天没时间，我尽快吧。你能写不😀 只需要写个类继承NotificationHandle，然后在NotificationHandle的工厂类里添加判断就行了。

**Comment by xinlanlan** [comment]
> 这几天没时间，我尽快吧。你能写不😀 只需要写个类继承NotificationHandle，然后在NotificationHandle的工厂类里添加判断就行了。

恩恩。我主要是写js的，我让朋友看看就好，主要是想让大神写用你的完整版本感觉内心踏实😀
好的，我自己试着先写

**Comment by WeihuaGu** [comment]
农信易扫的下载地址是哪？我没找到官网
