### ISSUE TITLE
能否将最新版的apk包传github上

### ISSUE THREAD

**Issue by 772875181** [WeihuaGu/receiptnotice#51]
这个外面有老版本apk包，但是不支持云闪付 看你这更新了新的支持了云闪付 。要回去下Android studio 安装一堆依赖然后再编译。实在是不会呀。我Q772875181 也加你zfb好友了。谢谢大神了。安卓开发确实不会呀😭

**Comment by WeihuaGu** [comment]
Release 里的就是最新的，可以直接下载

**Comment by 772875181** [comment]
谢谢 找到了 支付宝已打赏50

**Comment by 772875181** [comment]
在code下面 分支旁边 不在源码里

**Comment by WeihuaGu** [comment]
好的。因为这样在同步代码时，会变小，所以多数项目都是在发布里的。
