### ISSUE TITLE
在首页下载的代码编译后post返回false

### ISSUE THREAD

**Issue by cqsn558** [WeihuaGu/receiptnotice#57]
因为首页的代码是更新了的，直接从这里下载的代码编译后能监控到推送，但是不能post到设置的地址，log返回是false，我用release里的1.1版源码编译后能正常post，请问使用更新后的代码为什么不能post到网址？更新后的APP是要怎么设置后才能post吗？

**Comment by WeihuaGu** [comment]
谷歌用androidx代替了原有的support的图形库，我只是更换了androidx。这个默认要用api28即以上（就是安卓9），我猜测是它默认阻止http请求，只允许https。我晚上回去看看:grin:

**Comment by WeihuaGu** [comment]
@cqsn558 我在我的本地试了一下，这回应该可以了，还是debug版下载.

**Comment by cqsn558** [comment]
我自己加了适配的代码，在我手机上可以请求http了，修改方法是在 res 下新增一个 network_security_config.xml 文件，内容如下：
<?xml version="1.0" encoding="utf-8"?>

<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
修改AndroidManifest.xml文件，增加android:networkSecurityConfig="@xml/network_security_config"，编译后就行了。
知道你是修改的哪些内容，还没来得及看代码。

**Comment by cqsn558** [comment]
我自己加了适配的代码，在我手机上可以请求http了，修改方法是在 res 下新增一个 network_security_config.xml 文件，内容如下：
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
修改AndroidManifest.xml文件，增加android:networkSecurityConfig="@xml/network_security_config"，编译后就行了。
知道你是修改的哪些内容，还没来得及看代码。

**Comment by cqsn558** [comment]
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>

**Comment by cqsn558** [comment]
我自己加了适配的代码，在我手机上可以请求http了，修改方法是在 res 下新增一个 network_security_config.xml 文件，内容如下：
`<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>`
修改AndroidManifest.xml文件，增加android:networkSecurityConfig="@xml/network_security_config"，编译后就行了。
知道你是修改的哪些内容，还没来得及看代码。

**Comment by WeihuaGu** [comment]
对的，加这个就行了:smile:
