### ISSUE TITLE
应用被杀重启后没有后台服务

### ISSUE THREAD

**Issue by sunshine2176** [WeihuaGu/receiptnotice#6]
应用被杀后重启，后台服务没有启动啊

**Comment by WeihuaGu** [comment]
被杀后再次启动时，服务不生效（没有bindService）,这是个坑……用adb dumpsys service notification就可以看到，肯定是enable里有，live里没有。 一般重启可以，但有些rom就不行。

感谢反馈，我再试试，看能不能部分解决

**Comment by yanpengqing** [comment]
小米手机杀死再也没有启动

**Comment by WeihuaGu** [comment]
@yanpengqing 应用管理里，把自启动打开，然后省电策略里设成无限制试试。
