### ISSUE TITLE
求助..输入POST地址后出现签名效验失败.有人可以帮我解决下问题?

### ISSUE THREAD

**Issue by ljun637** [WeihuaGu/receiptnotice#61]
![321](https://user-images.githubusercontent.com/58955439/71319131-2e33c480-24d5-11ea-83be-ed58f607660c.jpg) 这个推送记录的截图

**Comment by WeihuaGu** [comment]
这是你服务器返回的，你要看服务器是怎么返回的，只要是推送结果为true,就说明服务器接受到了正确的post推送。

**Comment by ljun637** [comment]
你好.. 因为我不知道问题出在哪里.. 然后对于程序这些我也不懂.. 但是我用别人发给我的就能够正常使用.. 但是使用新版的就不能正常使用.. 我把APP发给你.. 你帮我看看好? 谢谢了.

**Comment by WeihuaGu** [comment]
问题是，发来没有办法测试，从推送记录的截图看，客户断没有报任何错误，因为看不到服务端代码，不知道怎么处理的，是不是对deviceid进行了识别？还是啥的。
如果别人发给你的，也是从这里下载的，或者从酷安下载的，那应该是一样，要不就是他又进行了某些更改，然后再编译的。

**Comment by WeihuaGu** [comment]
@ljun637 你发下正常工作的那个的推送记录的截图，我比较下post json有啥不同

**Comment by ljun637** [comment]
大哥.. 源码肯定是你的源码..  只是他不知道做了什么改动.. 就可以成功的推送到客户端.. 而用你的就始终无法推送完整!

**Comment by WeihuaGu** [comment]
你发下可以的那个推送截图，关键是看他的这个发的json有没有添加其它的，签名校验失败就是加了验证的意思吧……

**Comment by ljun637** [comment]
大佬.. 这是正常与不正常的截图

**Comment by WeihuaGu** [comment]
看不到图啊

**Comment by ljun637** [comment]
大哥.. notifications@github.com 这个邮箱地址是你的??  我用了一个阿里云的邮箱发图给你拉

**Comment by WeihuaGu** [comment]
那是GitHub 人家官方的邮箱…
我的邮箱 weihuagu_work@163.com

**Comment by WeihuaGu** [comment]
你发的截图显示，修改的作者加了sign字段，因为不知道生成算法，所以你只能和修改作者取得联系了…
