### ISSUE TITLE
希望可以增加md5加密方式

### ISSUE THREAD

**Issue by emengweb** [WeihuaGu/receiptnotice#62]
借用您的app和另一位大神的后台，拼凑出来一套可以运行的支付系统，十分感激。
后台借用的yioMe/nodejs_wx_aipay_api，比较全面些，只是接口不同。目前他使用的加密方式为md5，希望app加密也可以支持md5形式的加密：`md5(md5(price + type) + secretkey) // 收款金额，收款方式(wechat/alipay)，密匙 注意此处的 + 是字符串拼接`

另外，请教下app端的加密，在服务端DES解密时是对post每个字段的内容都单独解密么？感谢

**Comment by emengweb** [comment]
或者不改动现有post字段结构，直接按每个字段 ：`md5(md5(price) + secretkey), md5(md5(type) + secretkey)`这样也许会更规范些

**Comment by WeihuaGu** [comment]
DES是这样。好的，我会增加md5的

**Comment by emengweb** [comment]
> DES是这样。好的，我会增加md5的

按照推荐的server端，在另外的nodejs项目中des解密失败，试了一个多小时，依然找不到原因TvT
期待md5加密！

**Comment by emengweb** [comment]
> DES是这样。好的，我会增加md5的

感谢大神~现在配合server酱，做了微信推送，方便监控付款通知 :P

**Comment by WeihuaGu** [comment]
我这两天糊涂了，MD5,你咋解密？md5,是种散列函数，它要和原值对应的啊…

**Comment by WeihuaGu** [comment]
MD5,不是加密算法，只是能产生一段信息摘要啊。

**Comment by emengweb** [comment]
> MD5,不是加密算法，只是能产生一段信息摘要啊。

这位大神的server端项目github.com/yioMe/nodejs_wx_aipay_ap，将md5加密后的字符串作为检验值，sign字段，post给服务端，服务端会同样运行md5，生成检验值，对比两个值是否一致，这样既不暴露密钥，又可以根据每次交易金额不同，产生不同的检验值，很巧妙的处理方法
md5产生的方法是，`md5(md5(price + type) + secretkey) // 收款金额，收款方式(wechat/alipay)，密匙 注意此处的 + 是字符串拼接`
这样付款方式甚至都不需要服务端二次检验，因为如果和账单信息对不上，sign的检验都通不过。
希望可以附加一个类似的检验呢⊙∀⊙！ des的我从您服务端项目改进了下，可是不知什么原因，始终无法正确取得解密后的数据。

**Comment by emengweb** [comment]
> MD5,不是加密算法，只是能产生一段信息摘要啊。

不解密，只是作为密钥检验的方法

**Comment by WeihuaGu** [comment]
这个好，那我就默认增加一个sign字段。区别是，如果加密里选md5,就是md5(md5(price + type) + secretkey)，否则就是md5(md5(price + type))

**Comment by emengweb** [comment]
> 这个好，那我就默认增加一个sign字段。区别是，如果加密里选md5,就是md5(md5(price + type) + secretkey)，否则就是md5(md5(price + type))

谢谢大大！

**Comment by WeihuaGu** [comment]
@emengweb 我已经增加了这个sign字段。

**Comment by gengchen528** [comment]
> @emengweb 我已经增加了这个sign字段。

能重新打个最新的包么 谢谢啦

**Comment by WeihuaGu** [comment]
@gengchen528 可以先使用release里的那个最新debug版
