### ISSUE TITLE
部分安卓系统点菜单中“推送记录”会退出程序

### ISSUE THREAD

**Issue by cqsn558** [WeihuaGu/receiptnotice#71]
测试了华为安卓6、9、10和夜神模拟器安卓5点菜单中“推送记录”就会退出重启程序，夜神模板器安卓7正常。好像从2月15日“更改项目名称为接收推送 #68”更新后就存在这个问题了，请作者测试一下，谢谢！

**Comment by WeihuaGu** [comment]
应该是已经好了，这是因为重构时，只改变了java代码,xml设置文件中的包名没换过来。
________________________________
发件人: cqsn558 <notifications@github.com>
发送时间: 2020年2月19日 12:39
收件人: WeihuaGu/receiptnotice <receiptnotice@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [WeihuaGu/receiptnotice] 部分安卓系统点菜单中“推送记录”会退出程序 (#71)


测试了华为安卓6、9、10和夜神模拟器安卓5点菜单中“推送记录”就会退出重启程序，夜神模板器安卓7正常。好像从2月15日“更改项目名称为接收推送 #68<https://github.com/WeihuaGu/receiptnotice/issues/68>”更新后就存在这个问题了，请作者测试一下，谢谢！

―

**Comment by cqsn558** [comment]
我已经将app目录删除用最新下载的文件全部覆盖了（以前是只覆盖最新文件），重新编译后还是同样问题，按理其他文件不需要覆盖吧？

**Comment by WeihuaGu** [comment]
@cqsn558 你再下载更新一下，或者最简单，修改receiptnotice/app/src/main/res/xml/pref_general.xml里，把com.weihuagu.receiptnotice.FileLogActivity改成com.weihuagu.receiptnotice.view.FileLogActivity
