### ISSUE TITLE
支付宝和微信都不能截取消息

### ISSUE THREAD

**Issue by cqsn558** [WeihuaGu/receiptnotice#73]
最近下载了源码生成了APP，测试了下支付宝和微信都截取不到消息，看了下记录，好像截取的包名为null，试着发了微信消息，APP就会退出重启，调试界面显示是接受到支付类APP消息，包名是null。有些APP的消息可以接收到。
图片放在百度网盘：
链接：https://pan.baidu.com/s/1lhe12iXLLBEYw1q7IciMdA 
提取码：s3gg

**Comment by cqsn558** [comment]
另外试了下收短信也会导致APP退出重启。

**Comment by WeihuaGu** [comment]
感谢反馈，master有时因为添加代码而会有出现bug的问题，稳妥起见，先使用release

**Comment by cqsn558** [comment]
希望能尽快提交最新的，我还是比较喜欢用即时更新的，知道每次都改了哪些文件。

**Comment by WeihuaGu** [comment]
@cqsn558 bug应该是修复了

**Comment by cqsn558** [comment]
已经修复了，感谢！
