### ISSUE TITLE
可以增加微信的监听推送赞赏码嘛？

### ISSUE THREAD

**Issue by jamca012** [WeihuaGu/receiptnotice#79]
微信支付里面提示：二维码赞赏到账1元

**Comment by WeihuaGu** [comment]
微信现在还做不到应用内监听

**Comment by jamca012** [comment]
不是在应用里面啊，通知也会提示 二维码赞赏到账1元  
![微信图片_20200310142723](https://user-images.githubusercontent.com/61987006/76285704-56181480-62db-11ea-8ceb-0f9dd4c5938d.jpg)

**Comment by WeihuaGu** [comment]
可以添加
