### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by ientium** [WeihuaGu/receiptnotice#9]
手机端加入密钥设定，已保证和服务器端通讯包加密，手机端加入设定标识tag，发送给服务端来区分手机，实现多手机并发。要是能解出微信付款码的生成算法就完美了

**Comment by WeihuaGu** [comment]
第一个我也想到了，最后一个，研究下，可能希望不大🙄

**Comment by pan427pzh** [comment]
后期小建议：建立本地数据库，对通知进行收集，
IncorrectOrder	商户网站不存在该订单
Fail	金额不符或Sign验证失败
Success	通知成功
对Success	标示通知成功
对Fail返回的重复通知，通知3次后，标示放弃通知。
对IncorrectOrder标示订单不存在。

**Comment by pan427pzh** [comment]
需要服务器反馈该参数

**Comment by ientium** [comment]
> 后期小建议：建立本地数据库，对通知进行收集，
> IncorrectOrder	商户网站不存在该订单
> Fail	金额不符或Sign验证失败
> Success	通知成功
> 对Success	标示通知成功
> 对Fail返回的重复通知，通知3次后，标示放弃通知。
> 对IncorrectOrder标示订单不存在。

要在手机上生成单日志，对单？

**Comment by daniuwo** [comment]
我写了个后端欢迎测试
codepay.daniuwo.com
